        </main>

        <script type="text/javascript" src="/scripts/jquery-3.6.0.js"></script>
        <script type="text/javascript" src="/scripts/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript" src="/scripts/plutotool.js"></script>
        <script type="text/javascript" src="/scripts/DataTables/datatables.js"></script>

        <!-- Date time picker functionality -->
        <script type="text/javascript" src="/scripts/popperjs/2.11.6/popper.min.js"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script> -->
        <script type="text/javascript" src="/scripts/tempusdominus/6.0.1/js/tempus-dominus.js"></script>

    </body>
</html>