<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            
        <meta name="description" content="">
        <meta name="author" content="Marco Giammarini">
        <title><?php echo PRJ_NAME;?> - Beneficiari</title>

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" type="text/css" href="/scripts/bootstrap/5.1.3/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/styles/bootstrap-icons/1.6.1/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="/scripts/DataTables/datatables.css"/>

        <!-- Custom styles -->
        <link href="/styles/plutotool.css" rel="stylesheet">
    </head>
    <body>

        <header class="p-2 bg-dark text-white shadow">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none navbar-brand">
                    <?php echo PRJ_NAME . " " . PRJ_VERSION;?>
                    </a>
                </div>
            </div>
        </header>

        <main>