<?php
/*
 * This file is part of PlutoTool Project
 * Copyright (C) 2022 Marco Giammarini
 *
 * Author(s):
 *  Marco Giammarini <m.giammarini@warcomeb.it>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */
$displayType = ($type == "view") ? "disabled" : "";
$isError = FALSE;
$rows = NULL;

if (($type == "view") || ($type == "edit"))
{
    $query = "SELECT V.Id, V.Name, V.Maker, V.Model, V.Plate, V.Active, V.Note, V.PurchaseDate, " .
             "T.Name as TypeName, T.Id as TypeId " .
             "FROM " . PRJ_DB_TABLE_VEHICLE . " V " .
             "JOIN " . PRJ_DB_TABLE_VEHICLE_TYPE . " T ON V.VehicleTypeId=T.Id " .
             "WHERE V.Id={$_GET['id']}";

    $result = $db->query($query);
    if ($result)
    {
        $rows = $result->fetchAll(PDO::FETCH_ASSOC);
        if ((count($rows) == 0) || (count($rows) > 1))
        {
            $isError = TRUE;
        }
    }
    else
    {
        $isError = TRUE;
    }
}

if ($isError == FALSE)
{
?>
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2" id="vehicle-page-title">
            <?php  
                if      ($type == "view") echo "Visualizza Veicolo";
                else if ($type == "add")  echo "Nuovo Veicolo";
                else if ($type == "edit") echo "Modifica Veicolo";
            ?>
        </h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a class="btn btn-sm btn-outline-primary" href="/records/vehicle/index.php" role="button"><i class="bi bi-arrow-left-square"></i>&nbsp;Indietro</a>
            </div>
        </div>
    </div> 

    <div class="card mb-3">
        <div class="card-body">
            <form id="vehicle-form" class="row g-3" data-parsley-validate="">
                <input type="hidden" id="vehicle-form-type" value="<?php echo $type ?>" />

                <div class="form-group col-md-2">
                    <label for="vehicle-form-id">Id</label>
                    <input type="text" class="form-control" id="vehicle-form-id" placeholder="" value="<?php echo (isset($rows[0]['Id'])) ? $rows[0]['Id'] : "0"; ?>" disabled>
                </div>
                <div class="form-group col-md-10">
                    <label for="vehicle-form-name">Nome</label>
                    <input type="text" class="form-control" id="vehicle-form-name" placeholder="" data-parsley-minlength="3" autocomplete="off" required value="<?php echo (isset($rows[0]['Name'])) ? $rows[0]['Name'] : ""; ?>" <?php echo $displayType; ?>>
                </div>

                <div class="form-group col-md-6">
                    <label for="vehicle-form-maker">Azienda Produttrice</label>
                    <input type="text" class="form-control" id="vehicle-form-maker" placeholder="" data-parsley-minlength="3" autocomplete="off" value="<?php echo (isset($rows[0]['Maker'])) ? $rows[0]['Maker'] : ""; ?>" <?php echo $displayType; ?>>
                </div>

                <div class="form-group col-md-6">
                    <label for="vehicle-form-model">Modello</label>
                    <input type="text" class="form-control" id="vehicle-form-model" placeholder="" data-parsley-minlength="3" autocomplete="off" value="<?php echo (isset($rows[0]['Model'])) ? $rows[0]['Model'] : ""; ?>" <?php echo $displayType; ?>>
                </div>

                <div class="form-group col-md-6">
                    <label for="vehicle-form-plate">Targa</label>
                    <input type="text" class="form-control" id="vehicle-form-plate" placeholder="" data-parsley-minlength="6" autocomplete="off" value="<?php echo (isset($rows[0]['Plate'])) ? $rows[0]['Plate'] : ""; ?>" <?php echo $displayType; ?>>
                </div>

                <div class="form-group col-md-6">
                    <label for="vehicle-form-purchase">Data di Acquisto</label>
                    <div class="input-group date" id="vehicle-form-purchase1" data-target-input="nearest">                        	
                        <input type="text" class="form-control datetimepicker-input" data-target="#vehicle-form-purchase1" id="vehicle-form-purchase" value="<?php echo (isset($rows[0]['PurchaseDate'])) ? date("m/d/Y", strtotime($rows[0]['PurchaseDate'])) : ""; ?>" data-parsley-mydate="" data-parsley-errors-container="#parsley-datetimepicker-error1" required  <?php echo $displayType; ?>/>
                        <div class="input-group-append" data-target="#vehicle-form-purchase1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="bi bi-calendar2"></i></div>
                        </div>
                    </div>
                </div>

                <div class="form-group col-md-1">
                    <label for="vehicle-form-status">Status</label>
                    <div class="btn-group-toggle"  data-toggle="buttons">
<?php
if ($type == "view")
{
    echo "<input class=\"btn-check\" type=\"checkbox\" autocomplete=\"off\" id=\"vehicle-form-status\" disabled " . (($rows[0]['Active'] == 1) ? "checked" : "") . ">\n\t" .
         "<label class=\"btn btn-primary\">Attivo</label>\n";
}
else if ($type == "add")
{
    echo "<input class=\"btn-check\" type=\"checkbox\" autocomplete=\"off\" id=\"vehicle-form-status\" disabled checked>\n\t" .
         "<label class=\"btn btn-primary\">Attivo</label>\n";
}
else // Edit
{
    echo "<input class=\"btn-check\" type=\"checkbox\" autocomplete=\"off\" id=\"vehicle-form-status\" " . (($rows[0]['Active'] == 1) ? "checked" : "") . ">\n\t" .
         "<label class=\"btn btn-outline-primary\" for=\"vehicle-form-status\">Attivo</label>\n";
}
?>
                    </div>
                </div>

                <div class="form-group col-md-11">
                    <label for="vehicle-form-vtype">Tipo</label>
                    <div class="btn-group-toggle" data-toggle="buttons">
<?php
    if ($type === "view")
    {
        echo "<input type=\"text\" class=\"form-control\" id=\"vehicle-form-vtype\" placeholder=\"{$rows[0]['TypeName']}\" disabled>";
    }
    else
    {
        $query = "SELECT * FROM " . PRJ_DB_TABLE_VEHICLE_TYPE . " ORDER BY Name";

        $typeid = (isset($rows[0]['TypeId']) ? $rows[0]['TypeId'] : 0);
        $result = $db->query($query);
        if ($result)
        {
            $rowsVehicleType = $result->fetchAll(PDO::FETCH_ASSOC);
            if ($rowsVehicleType)
            {
                echo "<select id=\"vehicle-form-vtype\" class=\"form-control selectpicker\">\n";
                foreach ($rowsVehicleType as $rowVehicleType)
                {
                    $selected = "";
                    if ($rowVehicleType['Id'] === $typeid) $selected = "selected";
                    else $selected = "";
                
                    echo "<option value=\"{$rowVehicleType['Id']}\" {$selected}>{$rowVehicleType['Name']}</option>\n";
                }
                echo "</select>\n";
            }
        }                            
    }
?>         
                    </div>
                </div>

                <div class="form-group">
                    <label for="vehicle-form-note">Note</label>
                    <textarea class="form-control" id="vehicle-form-note" rows="3" placeholder="" <?php echo $displayType; ?>><?php echo (isset($rows[0]['Note']) ? $rows[0]['Note'] : ""); ?></textarea>
                </div>

<?php 
    if ($type != "view")
    {
?>
                <div class="form-group">
                    <button class="btn btn-primary"  onclick="save_vehicle()" id="vehicle-form-save">Save</button>
                    <button class="btn btn-primary" type="reset" id="vehicle-form-reset">Reset</button>
                </div>

                <div class="alert alert-success d-none" role="alert" id="vehicle-form-success">
                    &nbsp;
                </div>
                                
                <div class="alert alert-danger d-none" role="alert" id="vehicle-form-error">
                    &nbsp;
                </div>
                                
                <div class="alert alert-primary d-none" role="alert" id="vehicle-form-loading">
                    <div class="spinner-border spinner-border-sm" role="status">
                        <!-- <span class="visually-hidden">Loading...</span> -->
                    </div>
                    &nbsp; <span>Loading...</span>
                </div>
<?php
    }
?>
            </form>
        </div>
    </div>
</div>

<?php
}
else
{
    // TODO
}
?>